### obtener todos los games (paginado)
GET http://localhost:3000/api/games?page=1&limit=10

### obtener todos los games (sin paginar)
GET http://localhost:3000/api/games/?all=true

### obtener un game
GET http://localhost:3000/api/games/4

### crear un nuevo game
POST http://localhost:3000/api/games
Content-Type: application/json

{
  "name": "GTA 5",
  "description": "Juego de mundo abierto",
  "genre": "action"
}

### modificar un game (PATCH - recurso parcial)
PATCH http://localhost:3000/api/games/4
Content-Type: application/json

{
  "description": "Descripción actualizada sin tocar el nombre",
  "genre": "adventure"
}

### borrar un game
DELETE http://localhost:3000/api/games/1