CREATE TABLE IF NOT EXISTS reviews (
  id SERIAL PRIMARY KEY,
  gameTitle VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  score INTEGER NOT NULL CHECK (score >= 1 AND score <= 5),
  author VARCHAR(100) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);