### Login con username
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "john",
  "password": "password123"
}

### Login con email
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "john@example.com",
  "password": "password123"
}
